prices:
  gke:
    autopilot:
      spot:
        cpu: 11
        ram: 1
      regular:
        cpu: 36
        ram: 4
    standard:
      spot:
        cpu: 7
        ram: 1
      regular:
        cpu: 30
        ram: 3
namespaces:
  excluded:
    - 'gke-gmp-system'
    - 'gke-managed-filestorecsi'
    - 'gmp-public'
    - 'kube-node-lease'
    - 'kube-public'
    - 'kube-system'